name: Continuos Integration of Python Code

on: [push, pull_request]
# branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running unit tests with pytest
      run: |
        export PYTHONPATH=src
        pytest tests/test.py
    - name: Deploying app in Heroku
      env:
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        HEROKU_DOMAIN_APP: ${{ secrets.HEROKU_DOMAIN_APP }}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_TOKEN@git.heroku.com/$HEROKU_DOMAIN_APP.git      
        git push heroku HEAD:main -f
    - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          minor-wording:  'add,Adds,new,added'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes,fixed,patched'
          rc-wording:     'RELEASE,alpha'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
    
 